version: '3.7'

services:

  contacts.api.unit:
    image: nibro7778/contacts.api
    build:
      context: .
      dockerfile: src/Services/Contacts Service/Contacts.API/Dockerfile
      target: unit
    entrypoint:
      - dotnet
      - test